name: hand_bill_manger
description: A new Flutter application.

version: 1.2.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  dots_indicator: ^2.0.0
  intl: ^0.17.0
  video_player: ^2.1.14
  chewie: ^1.2.2
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.0.8
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
#  provider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^2.0.0
#  flutter_html: ^2.1.1
#  html: ^0.15.0
  google_nav_bar: ^5.0.5
  flutter_staggered_grid_view: ^0.4.0
  flutter_toggle_tab: ^1.1.6
#  firebase_auth: ^3.0.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
#  cloud_firestore: ^2.4.0
  flutter_local_notifications: ^8.1.1+1
  url_launcher: ^6.0.9
  collection: ^1.15.0-nullsafety.4
  image_picker: ^0.8.4
  pin_code_fields: ^7.3.0
  timeago: ^3.1.0
  flutter_datetime_picker: ^1.5.1
#  clipboard: ^0.1.3
  flutter_screenutil: ^5.1.0
  flutter_credit_card: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  syncfusion_flutter_datepicker: ^19.4.38
  intl_phone_field: ^3.1.0
  flutter_translate: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/account/
    - assets/i18n/en.json
    - assets/i18n/ar.json